//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSuitRepository.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eSuiteEntities : DbContext
    {
        public eSuiteEntities()
            : base("name=eSuiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SECURITY_MenuAccess> SECURITY_MenuAccess { get; set; }
        public virtual DbSet<SECURITY_User> SECURITY_User { get; set; }
        public virtual DbSet<SECURITY_UserGroup> SECURITY_UserGroup { get; set; }
        public virtual DbSet<SETUP_City> SETUP_City { get; set; }
        public virtual DbSet<SETUP_Company> SETUP_Company { get; set; }
        public virtual DbSet<SETUP_Country> SETUP_Country { get; set; }
        public virtual DbSet<SETUP_Customer> SETUP_Customer { get; set; }
        public virtual DbSet<SETUP_CustomerDlvryAdd> SETUP_CustomerDlvryAdd { get; set; }
        public virtual DbSet<SETUP_CustomerType> SETUP_CustomerType { get; set; }
        public virtual DbSet<SETUP_Department> SETUP_Department { get; set; }
        public virtual DbSet<SETUP_Location> SETUP_Location { get; set; }
        public virtual DbSet<SETUP_ProductGroup> SETUP_ProductGroup { get; set; }
        public virtual DbSet<SETUP_SalesArea> SETUP_SalesArea { get; set; }
        public virtual DbSet<SETUP_SalesAreaDetail> SETUP_SalesAreaDetail { get; set; }
        public virtual DbSet<SETUP_Unit> SETUP_Unit { get; set; }
        public virtual DbSet<SYS_Menu> SYS_Menu { get; set; }
        public virtual DbSet<SYS_Parameter> SYS_Parameter { get; set; }
    }
}
