//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSuitRepository.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECURITY_User
    {
        public SECURITY_User()
        {
            this.SECURITY_MenuAccess = new HashSet<SECURITY_MenuAccess>();
        }
    
        public int Usr_Id { get; set; }
        public string Usr_Code { get; set; }
        public Nullable<int> Comp_Id { get; set; }
        public Nullable<int> UsrGrp_Id { get; set; }
        public string Usr_Desc { get; set; }
        public string Usr_ShortDesc { get; set; }
        public Nullable<int> Usr_Status { get; set; }
        public Nullable<int> Usr_SortOrder { get; set; }
        public string Usr_LoginId { get; set; }
        public string Usr_Password { get; set; }
        public string Usr_EmployeeCode { get; set; }
        public string Usr_DefaultModule { get; set; }
    
        public virtual ICollection<SECURITY_MenuAccess> SECURITY_MenuAccess { get; set; }
        public virtual SETUP_Company SETUP_Company { get; set; }
        public virtual SECURITY_UserGroup SECURITY_UserGroup { get; set; }
    }
}
