//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSuitRepository.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECURITY_UserGroup
    {
        public SECURITY_UserGroup()
        {
            this.SECURITY_User = new HashSet<SECURITY_User>();
        }
    
        public int UsrGrp_Id { get; set; }
        public string UsrGrp_Code { get; set; }
        public Nullable<int> Comp_Id { get; set; }
        public string UsrGrp_Desc { get; set; }
        public string UsrGrp_ShortDesc { get; set; }
        public Nullable<int> UsrGrp_Status { get; set; }
        public Nullable<int> UsrGrp_SortOrder { get; set; }
    
        public virtual ICollection<SECURITY_User> SECURITY_User { get; set; }
        public virtual SETUP_Company SETUP_Company { get; set; }
    }
}
