//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSuitRepository.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETUP_Company
    {
        public SETUP_Company()
        {
            this.SECURITY_MenuAccess = new HashSet<SECURITY_MenuAccess>();
            this.SECURITY_User = new HashSet<SECURITY_User>();
            this.SECURITY_UserGroup = new HashSet<SECURITY_UserGroup>();
            this.SETUP_Country = new HashSet<SETUP_Country>();
            this.SETUP_Customer = new HashSet<SETUP_Customer>();
            this.SETUP_CustomerDlvryAdd = new HashSet<SETUP_CustomerDlvryAdd>();
            this.SETUP_CustomerType = new HashSet<SETUP_CustomerType>();
            this.SETUP_Department = new HashSet<SETUP_Department>();
            this.SETUP_Location = new HashSet<SETUP_Location>();
            this.SYS_Menu = new HashSet<SYS_Menu>();
            this.SETUP_ProductGroup = new HashSet<SETUP_ProductGroup>();
            this.SETUP_SalesArea = new HashSet<SETUP_SalesArea>();
            this.SETUP_Unit = new HashSet<SETUP_Unit>();
            this.SETUP_City = new HashSet<SETUP_City>();
        }
    
        public int Comp_Id { get; set; }
        public string Comp_Code { get; set; }
        public string Comp_Desc { get; set; }
        public string Comp_ShortDesc { get; set; }
        public Nullable<int> Comp_Status { get; set; }
        public Nullable<int> Comp_SortOrder { get; set; }
        public string Comp_NTN { get; set; }
        public string Comp_Address1 { get; set; }
        public string Comp_Address2 { get; set; }
        public string Comp_Address3 { get; set; }
        public string Comp_Address4 { get; set; }
        public string Comp_Phone1 { get; set; }
        public string Comp_Phone2 { get; set; }
        public string Comp_Phone3 { get; set; }
        public string Comp_Mobile1 { get; set; }
        public string Comp_Mobile2 { get; set; }
        public string Comp_Fax { get; set; }
        public string Comp_EMail { get; set; }
        public string Comp_WEB { get; set; }
        public string Comp_ContactPerson { get; set; }
    
        public virtual ICollection<SECURITY_MenuAccess> SECURITY_MenuAccess { get; set; }
        public virtual ICollection<SECURITY_User> SECURITY_User { get; set; }
        public virtual ICollection<SECURITY_UserGroup> SECURITY_UserGroup { get; set; }
        public virtual ICollection<SETUP_Country> SETUP_Country { get; set; }
        public virtual ICollection<SETUP_Customer> SETUP_Customer { get; set; }
        public virtual ICollection<SETUP_CustomerDlvryAdd> SETUP_CustomerDlvryAdd { get; set; }
        public virtual ICollection<SETUP_CustomerType> SETUP_CustomerType { get; set; }
        public virtual ICollection<SETUP_Department> SETUP_Department { get; set; }
        public virtual ICollection<SETUP_Location> SETUP_Location { get; set; }
        public virtual ICollection<SYS_Menu> SYS_Menu { get; set; }
        public virtual ICollection<SETUP_ProductGroup> SETUP_ProductGroup { get; set; }
        public virtual ICollection<SETUP_SalesArea> SETUP_SalesArea { get; set; }
        public virtual ICollection<SETUP_Unit> SETUP_Unit { get; set; }
        public virtual ICollection<SETUP_City> SETUP_City { get; set; }
    }
}
