//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSuitRepository.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETUP_ProductGroup
    {
        public int ProdGrp_Id { get; set; }
        public string ProdGrp_Code { get; set; }
        public Nullable<int> Comp_Id { get; set; }
        public string ProdGrp_Desc { get; set; }
        public string ProdGrp_ShortDesc { get; set; }
        public Nullable<int> ProdGrp_Status { get; set; }
        public Nullable<int> ProdGrp_SortOrder { get; set; }
        public Nullable<int> ProdGrp_Level { get; set; }
    
        public virtual SETUP_Company SETUP_Company { get; set; }
    }
}
