//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSuitRepository.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETUP_Location
    {
        public int Loc_Id { get; set; }
        public string Loc_Code { get; set; }
        public Nullable<int> Comp_Id { get; set; }
        public string Loc_Desc { get; set; }
        public string Loc_ShortDesc { get; set; }
        public Nullable<int> Loc_Status { get; set; }
        public Nullable<int> Loc_SortOrder { get; set; }
        public string Loc_Address1 { get; set; }
        public string Loc_Address2 { get; set; }
        public string Loc_Address3 { get; set; }
        public string Loc_Address4 { get; set; }
        public string Loc_Phone1 { get; set; }
        public string Loc_Phone2 { get; set; }
        public string Loc_Phone3 { get; set; }
        public string Loc_Mobile1 { get; set; }
        public string Loc_Mobile2 { get; set; }
        public string Loc_Fax { get; set; }
        public string Loc_EMail { get; set; }
        public string Loc_ContactPerson { get; set; }
    
        public virtual SETUP_Company SETUP_Company { get; set; }
    }
}
