//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSuitRepository.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETUP_City
    {
        public SETUP_City()
        {
            this.SETUP_Customer = new HashSet<SETUP_Customer>();
            this.SETUP_SalesAreaDetail = new HashSet<SETUP_SalesAreaDetail>();
        }
    
        public int City_Id { get; set; }
        public string City_Code { get; set; }
        public Nullable<int> Comp_Id { get; set; }
        public Nullable<int> Cont_Id { get; set; }
        public string City_Desc { get; set; }
        public string City_ShortDesc { get; set; }
        public Nullable<int> City_Status { get; set; }
        public Nullable<int> City_SortOrder { get; set; }
    
        public virtual ICollection<SETUP_Customer> SETUP_Customer { get; set; }
        public virtual ICollection<SETUP_SalesAreaDetail> SETUP_SalesAreaDetail { get; set; }
        public virtual SETUP_Company SETUP_Company { get; set; }
        public virtual SETUP_Country SETUP_Country { get; set; }
    }
}
