//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSuitRepository.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETUP_Customer
    {
        public SETUP_Customer()
        {
            this.SETUP_CustomerDlvryAdd = new HashSet<SETUP_CustomerDlvryAdd>();
        }
    
        public int Cst_Id { get; set; }
        public string Cst_Code { get; set; }
        public Nullable<int> Comp_Id { get; set; }
        public Nullable<int> CstTyp_Id { get; set; }
        public string Cst_Name { get; set; }
        public Nullable<int> Cont_Id { get; set; }
        public Nullable<int> City_Id { get; set; }
        public string Cst_Address1 { get; set; }
        public string Cst_Address2 { get; set; }
        public string Cst_Address3 { get; set; }
        public string Cst_Address4 { get; set; }
        public string Cst_Phone1 { get; set; }
        public string Cst_Phone2 { get; set; }
        public string Cst_Phone3 { get; set; }
        public string Cst_Mobile1 { get; set; }
        public string Cst_Mobile2 { get; set; }
        public string Cst_Fax { get; set; }
        public string Cst_EMail { get; set; }
        public string Cst_ContactPerson { get; set; }
        public Nullable<int> Cst_Status { get; set; }
    
        public virtual SETUP_City SETUP_City { get; set; }
        public virtual SETUP_Company SETUP_Company { get; set; }
        public virtual SETUP_Country SETUP_Country { get; set; }
        public virtual ICollection<SETUP_CustomerDlvryAdd> SETUP_CustomerDlvryAdd { get; set; }
        public virtual SETUP_CustomerType SETUP_CustomerType { get; set; }
    }
}
