//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSuitRepository.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETUP_Unit
    {
        public int Unit_Id { get; set; }
        public string Unit_Code { get; set; }
        public Nullable<int> Comp_Id { get; set; }
        public string Unit_Desc { get; set; }
        public string Unit_ShortDesc { get; set; }
        public Nullable<int> Unit_Status { get; set; }
        public Nullable<int> Unit_SortOrder { get; set; }
    
        public virtual SETUP_Company SETUP_Company { get; set; }
    }
}
