//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSuitRepository.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETUP_SalesArea
    {
        public SETUP_SalesArea()
        {
            this.SETUP_SalesAreaDetail = new HashSet<SETUP_SalesAreaDetail>();
        }
    
        public int SalAr_Id { get; set; }
        public string SalAr_Code { get; set; }
        public Nullable<int> Comp_Id { get; set; }
        public string SalAr_Desc { get; set; }
        public string SalAr_ShortDesc { get; set; }
        public Nullable<int> SalAr_Status { get; set; }
        public Nullable<int> SalAr_SortOrder { get; set; }
        public Nullable<int> SalAr_Level { get; set; }
    
        public virtual SETUP_Company SETUP_Company { get; set; }
        public virtual ICollection<SETUP_SalesAreaDetail> SETUP_SalesAreaDetail { get; set; }
    }
}
