//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSuitRepository.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETUP_Country
    {
        public SETUP_Country()
        {
            this.SETUP_Customer = new HashSet<SETUP_Customer>();
            this.SETUP_City = new HashSet<SETUP_City>();
        }
    
        public int Cont_Id { get; set; }
        public string Cont_Code { get; set; }
        public Nullable<int> Comp_Id { get; set; }
        public string Cont_Continent { get; set; }
        public string Cont_Desc { get; set; }
        public string Cont_ShortDesc { get; set; }
        public Nullable<int> Cont_Status { get; set; }
        public Nullable<int> Cont_SortOrder { get; set; }
    
        public virtual SETUP_Company SETUP_Company { get; set; }
        public virtual ICollection<SETUP_Customer> SETUP_Customer { get; set; }
        public virtual ICollection<SETUP_City> SETUP_City { get; set; }
    }
}
