//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSuitRepository.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETUP_CustomerType
    {
        public SETUP_CustomerType()
        {
            this.SETUP_Customer = new HashSet<SETUP_Customer>();
        }
    
        public int CstTyp_Id { get; set; }
        public string CstTyp_Code { get; set; }
        public Nullable<int> Comp_Id { get; set; }
        public string CstTyp_Desc { get; set; }
        public string CstTyp_ShortDesc { get; set; }
        public Nullable<int> CstTyp_Status { get; set; }
        public Nullable<int> CstTyp_SortOrder { get; set; }
    
        public virtual SETUP_Company SETUP_Company { get; set; }
        public virtual ICollection<SETUP_Customer> SETUP_Customer { get; set; }
    }
}
