//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSuitRepository.DataModels
{
    using System;
    using System.Collections.Generic;

    public partial class SETUP_Department
    {
        public int Dep_Id { get; set; }
        public string Dep_Code { get; set; }
        public Nullable<int> Comp_Id { get; set; }
        public Nullable<int> Dep_Level { get; set; }
        public string Dep_Desc { get; set; }
        public string Dep_ShortDesc { get; set; }
        public Nullable<int> Dep_Status { get; set; }
        public Nullable<int> Dep_SortOrder { get; set; }
        public string Dep_Phone1 { get; set; }
        public string Dep_Phone2 { get; set; }
        public string Dep_Phone3 { get; set; }
        public string Dep_Mobile1 { get; set; }
        public string Dep_Mobile2 { get; set; }
        public string Dep_Fax { get; set; }
        public string Dep_EMail { get; set; }
        public string Dep_ContactPerson { get; set; }

        public virtual SETUP_Company SETUP_Company { get; set; }
    }
}
