//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSuitRepository.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Parameter
    {
        public int SPara_Id { get; set; }
        public string SPara_Code { get; set; }
        public string SPara_Desc { get; set; }
        public string SPara_ShortDesc { get; set; }
        public Nullable<int> SPara_Status { get; set; }
        public string SPara_Value { get; set; }
        public string SPara_InputType { get; set; }
        public string SPara_InputOption { get; set; }
    }
}
